# Generated by Django 4.2.3 on 2023-10-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('price_range', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='property_images/')),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Property_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
